document.addEventListener('scroll', function() {
if(suggestions.getBoundingClientRect().y<81){
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('inactive');
    element.classList.add('active');
}
else if(boring.getBoundingClientRect().y<81){
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('inactive');
    element.classList.add('active');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('active');
    element.classList.add('inactive');
}
else if(culture.getBoundingClientRect().y<81){
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('inactive');
    element.classList.add('active');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('active');
    element.classList.add('inactive');
}
else if(agriculture.getBoundingClientRect().y<81){
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('inactive');
    element.classList.add('active');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('active');
    element.classList.add('inactive');
}
else if(industry.getBoundingClientRect().y<81){
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('inactive');
    element.classList.add('active');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('active');
    element.classList.add('inactive');
}
else if(medicine.getBoundingClientRect().y<81){
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('inactive');
    element.classList.add('active');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('active');
    element.classList.add('inactive');
}
else if(education.getBoundingClientRect().y<81){
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('inactive');
    element.classList.add('active');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('active');
    element.classList.add('inactive');
}
else{
    element = document.getElementById("NavBarBeginning");
    element.classList.remove('inactive');
    element.classList.add('active');
    element = document.getElementById("NavBarEducation");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarMedicine");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarIndustry");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarAgriculture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarCulture");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarBoring");
    element.classList.remove('active');
    element.classList.add('inactive');
    element = document.getElementById("NavBarSuggestions");
    element.classList.remove('active');
    element.classList.add('inactive');
}
});